### ISSUE TITLE
Support Requested

### ISSUE THREAD

**Issue by htarwara6245** [AhmedElassuty/IOS-BottomSheet#2]
First of all, thanks for wonderful explanation at SO.
- Rotating Support (There are some rotating problem if we set device orientation to rotate left and right)
- When we start loaded the app,the bottom sheet is on top and then go down (initial)
- Support for customizable scrollable point like iOS 10 map which we can set three point on screen(top,middle,down)

Thanks
Best Regards

**Comment by AhmedElassuty** [comment]
Thanks @htarwara6245 for your request. I'm planning to create a pod with more features and already started working on it but I'm really busy nowadays. I will include some of your suggestions and happy to hear more suggestions.

Thanks
