### ISSUE TITLE
Adding multiple bottom sheets

### ISSUE THREAD

**Issue by ajaybrach** [AhmedElassuty/IOS-BottomSheet#4]
Thanks @AhmedElassuty ! this has be a large help.

I was wondering if you had any tips on how to implement this code so that I can add multiple bottom sheets that go above one another. 

Do you suggest to addSubview within the first bottom sheet? or would I be addSubview to the original view?

Would really appreciate any direction you can give me here. Thanks!

**Comment by AhmedElassuty** [comment]
It depends on your needs.. but I think it would be better if you added the new view to the original view. This way If you removed the first bottom sheet from the hierarchy the other sheets would not be removed.

If you added it to the first bottom sheet, you may encounter some issues while handling the gestures.

Sorry for the late reply.
