### ISSUE TITLE
Need swift 2.3 version

### ISSUE THREAD

**Issue by SwiftisLife** [AhmedElassuty/IOS-BottomSheet#5]
Saw your repository on StackOverflow and noticed you originally wrote it in Swift 2.3 and later on migrated to Swift 3.0. Would be very interested in this project for Swift 2.3 if possible. 

Kind Regards, 

Alexandra

**Comment by AhmedElassuty** [comment]
Unfortunately, I cannot provide a version that supports Swift 2.3 right now. But I'm planning to create a pod with more features and I haven't decided yet which versions I would support.

Thanks
